ALLOWED_TRANSITIONS = {
    "IN_PROGRESS": {"APPROVED", "DECLINED", "FAILED", "CANCELED"},
    "APPROVED": {"APPROVED"},
    "DECLINED": {"DECLINED"},
    "FAILED": {"FAILED"},
    "CANCELED": {"CANCELED"},
}
